// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: pkg/pkginventory/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// APIResourcesClient is the client API for APIResources service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIResourcesClient interface {
	Get(ctx context.Context, in *Get_Request, opts ...grpc.CallOption) (*Get_Response, error)
}

type aPIResourcesClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIResourcesClient(cc grpc.ClientConnInterface) APIResourcesClient {
	return &aPIResourcesClient{cc}
}

func (c *aPIResourcesClient) Get(ctx context.Context, in *Get_Request, opts ...grpc.CallOption) (*Get_Response, error) {
	out := new(Get_Response)
	err := c.cc.Invoke(ctx, "/api.APIResources/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIResourcesServer is the server API for APIResources service.
// All implementations must embed UnimplementedAPIResourcesServer
// for forward compatibility
type APIResourcesServer interface {
	Get(context.Context, *Get_Request) (*Get_Response, error)
	mustEmbedUnimplementedAPIResourcesServer()
}

// UnimplementedAPIResourcesServer must be embedded to have forward compatible implementations.
type UnimplementedAPIResourcesServer struct {
}

func (UnimplementedAPIResourcesServer) Get(context.Context, *Get_Request) (*Get_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAPIResourcesServer) mustEmbedUnimplementedAPIResourcesServer() {}

// UnsafeAPIResourcesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIResourcesServer will
// result in compilation errors.
type UnsafeAPIResourcesServer interface {
	mustEmbedUnimplementedAPIResourcesServer()
}

func RegisterAPIResourcesServer(s grpc.ServiceRegistrar, srv APIResourcesServer) {
	s.RegisterService(&APIResources_ServiceDesc, srv)
}

func _APIResources_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIResourcesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.APIResources/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIResourcesServer).Get(ctx, req.(*Get_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// APIResources_ServiceDesc is the grpc.ServiceDesc for APIResources service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIResources_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.APIResources",
	HandlerType: (*APIResourcesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _APIResources_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pkginventory/api/api.proto",
}
